apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
